# Generated by Django 5.1.6 on 2025-04-13 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_treatmenthistory_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='schedule',
        ),
    ]
