# Generated by Django 5.1.6 on 2025-04-13 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_appointment_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmenthistory',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='treatmenthistory',
            name='treatment_date',
        ),
    ]
