# Generated by Django 5.1.6 on 2025-04-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_treatmenthistory_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.AddField(
            model_name='dentist',
            name='bio',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
