# Generated by Django 5.1.6 on 2025-04-13 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_patient_address_dentist_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dentist',
            old_name='specialty',
            new_name='speciality',
        ),
    ]
