# Generated by Django 5.1.6 on 2025-04-15 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_rename_specialty_dentist_speciality'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmenthistory',
            name='appointment',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='note',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='first_name',
            new_name='insurance_provider',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_time',
        ),
        migrations.RemoveField(
            model_name='dentist',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='dentist',
            name='email',
        ),
        migrations.RemoveField(
            model_name='dentist',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='dentist',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='dentist',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='dentist',
            name='speciality',
        ),
        migrations.RemoveField(
            model_name='dentist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.AddField(
            model_name='appointment',
            name='end',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='start',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='BlockedTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now=True)),
                ('end', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField(blank=True)),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_times', to='project.dentist')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('phone', models.TextField()),
                ('address', models.TextField()),
                ('image_file', models.ImageField(blank=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to='project.profile'),
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure', models.TextField()),
                ('tooth_number', models.TextField()),
                ('tooth_status', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='project.appointment')),
            ],
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='TreatmentHistory',
        ),
    ]
