# Generated by Django 5.1.6 on 2025-04-15 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_remove_treatmenthistory_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentist',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dentist',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dentist_profile', to='project.profile'),
        ),
        migrations.AddField(
            model_name='dentist',
            name='specialization',
            field=models.TextField(default='General'),
        ),
    ]
