# Generated by Django 5.1.6 on 2025-04-15 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_dentist_bio_dentist_profile_dentist_specialization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatment',
            old_name='notes',
            new_name='dentist_notes',
        ),
    ]
