# Generated by Django 5.1.6 on 2025-04-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_rename_notes_treatment_dentist_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='blockedtime',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='blockedtime',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
