# Generated by Django 5.1.6 on 2025-04-15 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_appointment_end_alter_appointment_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='tooth_status',
        ),
    ]
