# Generated by Django 5.1.6 on 2025-04-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_remove_treatment_tooth_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dentist',
            old_name='specialization',
            new_name='speciality',
        ),
        migrations.AlterField(
            model_name='treatment',
            name='dentist_notes',
            field=models.TextField(blank=True, default='No notes from dentist yet.'),
        ),
    ]
