# Generated by Django 5.1.6 on 2025-04-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_rename_specialization_dentist_speciality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='last_updated',
            field=models.BooleanField(default=False),
        ),
    ]
