# Generated by Django 5.1.6 on 2025-04-16 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_treatment_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='last_updated',
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
