# Generated by Django 5.1.6 on 2025-04-17 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_remove_treatment_last_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='blockedtime',
            name='dentist',
        ),
        migrations.RemoveField(
            model_name='dentist',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Treatment',
        ),
        migrations.DeleteModel(
            name='BlockedTime',
        ),
        migrations.DeleteModel(
            name='Dentist',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
