# Generated by Django 5.1.6 on 2025-03-03 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0004_remove_profile_profile_image_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusimage',
            old_name='StatusImage',
            new_name='StatusMessage',
        ),
    ]
