# Generated by Django 5.1.6 on 2025-03-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0005_rename_statusimage_statusimage_statusmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_image_url',
            new_name='profile_image_file',
        ),
        migrations.RenameField(
            model_name='statusimage',
            old_name='Image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='ImageField',
        ),
        migrations.AddField(
            model_name='image',
            name='caption',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='image',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
