# Generated by Django 5.1.6 on 2025-03-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0006_rename_profile_image_url_profile_profile_image_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image_file',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
