# Generated by Django 5.1.6 on 2025-03-04 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0007_alter_profile_profile_image_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_image_file',
            new_name='image_file',
        ),
        migrations.RenameField(
            model_name='statusimage',
            old_name='StatusMessage',
            new_name='status_message',
        ),
    ]
