# Generated by Django 5.1.6 on 2025-03-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0008_rename_profile_image_file_profile_image_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image_file',
        ),
        migrations.AddField(
            model_name='profile',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
