# Generated by Django 5.1.6 on 2025-03-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0010_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
